<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="CGSCLXI54290887" ignored="1" name="personal loan" tests="4" failures="1" timestamp="2020-04-04T12:53:42 IST" time="0.199" errors="0">
  <testcase name="demo1" time="0.021" classname="practise.Demo">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at practise.Demo.demo1(Demo.java:25)
at java.util.ArrayList.forEach(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- demo1 -->
  <testcase name="demo1" time="0.045" classname="practise.Demo1"/>
  <testcase name="demo" time="0.018" classname="practise.Demo"/>
  <testcase name="demo" time="0.009" classname="practise.Demo"/>
  <testcase name="demo" time="0.0" classname="practise.Demo1">
    <ignored/>
  </testcase> <!-- demo -->
</testsuite> <!-- personal loan -->
