<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="CGSCLXI54290887" ignored="0" name="retry test" tests="3" failures="2" timestamp="2020-04-02T18:47:34 IST" time="0.108" errors="0">
  <testcase name="test1" time="0.018" classname="practise.RunRetry">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at practise.RunRetry.test1(RunRetry.java:9)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.002" classname="practise.RunRetry"/>
  <testcase name="test3" time="0.002" classname="practise.RunRetry">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at practise.RunRetry.test3(RunRetry.java:19)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
</testsuite> <!-- retry test -->
